// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCluster) DeepCopyInto(out *RemoteCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCluster.
func (in *RemoteCluster) DeepCopy() *RemoteCluster {
	if in == nil {
		return nil
	}
	out := new(RemoteCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterList) DeepCopyInto(out *RemoteClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterList.
func (in *RemoteClusterList) DeepCopy() *RemoteClusterList {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterSpec) DeepCopyInto(out *RemoteClusterSpec) {
	*out = *in
	out.KubeconfigSecret = in.KubeconfigSecret
	out.ResyncInterval = in.ResyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterSpec.
func (in *RemoteClusterSpec) DeepCopy() *RemoteClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterState) DeepCopyInto(out *RemoteClusterState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterState.
func (in *RemoteClusterState) DeepCopy() *RemoteClusterState {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterStatus) DeepCopyInto(out *RemoteClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Remote = in.Remote
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterStatus.
func (in *RemoteClusterStatus) DeepCopy() *RemoteClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObject) DeepCopyInto(out *RemoteObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObject.
func (in *RemoteObject) DeepCopy() *RemoteObject {
	if in == nil {
		return nil
	}
	out := new(RemoteObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteObject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectList) DeepCopyInto(out *RemoteObjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectList.
func (in *RemoteObjectList) DeepCopy() *RemoteObjectList {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteObjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectPriorityClass) DeepCopyInto(out *RemoteObjectPriorityClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.ResyncInterval = in.ResyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectPriorityClass.
func (in *RemoteObjectPriorityClass) DeepCopy() *RemoteObjectPriorityClass {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectPriorityClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteObjectPriorityClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectPriorityClassList) DeepCopyInto(out *RemoteObjectPriorityClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteObjectPriorityClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectPriorityClassList.
func (in *RemoteObjectPriorityClassList) DeepCopy() *RemoteObjectPriorityClassList {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectPriorityClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteObjectPriorityClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectProbe) DeepCopyInto(out *RemoteObjectProbe) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(RemoteObjectProbeConditionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectProbe.
func (in *RemoteObjectProbe) DeepCopy() *RemoteObjectProbe {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectProbeConditionSpec) DeepCopyInto(out *RemoteObjectProbeConditionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectProbeConditionSpec.
func (in *RemoteObjectProbeConditionSpec) DeepCopy() *RemoteObjectProbeConditionSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectProbeConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectSpec) DeepCopyInto(out *RemoteObjectSpec) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	in.AvailabilityProbe.DeepCopyInto(&out.AvailabilityProbe)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectSpec.
func (in *RemoteObjectSpec) DeepCopy() *RemoteObjectSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectStatus) DeepCopyInto(out *RemoteObjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectStatus.
func (in *RemoteObjectStatus) DeepCopy() *RemoteObjectStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectStatus)
	in.DeepCopyInto(out)
	return out
}
